# Generated by Django 3.1.6 on 2021-02-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sername', models.CharField(max_length=300)),
                ('othername', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('adress', models.CharField(max_length=300)),
                ('poster', models.ImageField(upload_to='poster/')),
            ],
        ),
    ]
