# Generated by Django 3.1.3 on 2021-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_trener',
            field=models.BooleanField(null=True),
        ),
    ]
