# Generated by Django 3.1.5 on 2021-01-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userblog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
