# Generated by Django 3.1.3 on 2021-02-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210216_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trener',
            name='staj',
            field=models.CharField(max_length=10),
        ),
    ]
