# Generated by Django 3.1.3 on 2021-02-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210217_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trener',
            name='salary',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='trener',
            name='staj',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='trener',
            name='time_work',
            field=models.IntegerField(blank=True),
        ),
    ]
