# Generated by Django 3.1.3 on 2021-02-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210216_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_client',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_trener',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
