# Generated by Django 3.1.6 on 2021-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210217_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportproducts',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
    ]
